added `tf:optional` annotation to simplify the code
databricks/terraform-provider-databricks pull request #1395
Opened 2022-06-23 17:54 UTC by alexott

Quite often there are situations when field should be required in the JSON payload (so we send default values, such as `true`, `0`, ...) but it's really optional in the Terraform schema, so we need to explicitly modify the schema with code like:

```
m["enable_photon"].Optional = true
m["enable_photon"].Required = false
```

This patch adds the `optional` keyword that will be checked in the `tf` annotation, so we can avoid explicit schema modification

2022-06-24 08:20 UTC, nfx reviewed
this is a great change, though it requires a bit thorough integration testing. let's aim it for 1.1, as it changes schemas slightly

2022-07-07 13:14 UTC, alexott commented
it's covered by the unit test...

2022-07-12 14:55 UTC, alexott commented
@nfx I've added another test for SQL Endpoint that demonstrates that `tf:optional` works

2022-07-12 19:18 UTC, nfx commented
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/259697/178576280-099fcd59-5c4b-49cc-a284-d958804d5c95.png">

2022-07-12 19:38 UTC, nfx requested changes
Can you add few more unit tests?

2022-07-15 13:04 UTC, alexott commented on clusters/clusters_api.go
> +	File *LocalFileInfo   `json:"file,omitempty"`
yes, schema is the same

2022-07-17 18:38 UTC, nfx approved these changes

2022-07-17 18:38 UTC, merged