[BUG FIX] Cluster edit fails if cluster transitions into TERMINATED s…
databricks/terraform-provider-databricks pull request #1548
Opened 2022-08-17 22:05 UTC by shreyas-goenka

…tate from PENDING / RESIZING / RESTARTING states

2022-08-18 07:46 UTC, nfx requested changes

2022-08-18 07:46 UTC, nfx commented on clusters/clusters_api.go
> -		// let's wait tiny bit, so we return RUNNING cluster info
Can you have two branches: one where you wait for terminated, the other where you wait for running.

creating a method with duplicate logic is not a good idea

2022-08-18 07:46 UTC, nfx commented on clusters/clusters_api_test.go
> +				Message: "I am a teapot. The cutest little teapot.",
😂

HTTP 418 is real. https://www.rfc-editor.org/rfc/rfc2324#section-2.3.2

2022-08-22 10:00 UTC, shreyas-goenka commented
On further discussion, we decided to not merge this bug fix since resource_cluster is super critical, users are not expected to manually edit terraformed resources and retry by user is a very easy and valid workaround

2022-08-22 10:01 UTC, closed without merging