Minor changes to instance pool docs
databricks/terraform-provider-databricks pull request #1581
Opened 2022-09-05 15:42 UTC by iandexter

In relation to the following issues:

* https://github.com/databricks/terraform-provider-databricks/issues/1448
* https://github.com/databricks/terraform-provider-databricks/issues/1449

2022-09-05 15:44 UTC, alexott requested changes

2022-09-05 15:44 UTC, alexott commented on docs/resources/instance_pool.md
> +* `max_capacity` - (Optional) (Integer) The maximum number of instances the pool can contain, including both idle instances and ones in use by clusters. Once the maximum capacity is reached, you cann
Remove the next item then

2022-09-06 19:31 UTC, nfx approved these changes

2022-09-07 09:21 UTC, iandexter commented on docs/resources/instance_pool.md
> +* `max_capacity` - (Optional) (Integer) The maximum number of instances the pool can contain, including both idle instances and ones in use by clusters. Once the maximum capacity is reached, you cann
@alexott -- Removed the duplicate line.

2022-09-07 09:27 UTC, alexott approved these changes

2022-09-07 09:27 UTC, merged