Docs fix: minor errors in Unity Catalog docs
databricks/terraform-provider-databricks pull request #1626
Opened 2022-09-21 06:38 UTC by MigQ2

- Removed some references to Unity Catalog being in preview as [Unity Catalog is GA](https://docs.databricks.com/release-notes/product/2022/august.html#unity-catalog-is-ga)
- Fixed order of container and storage account in ADLS2 path

2022-09-22 08:35 UTC, nkvuong requested changes
Just a suggested change, but otherwise looks good to me

2022-09-22 08:35 UTC, nkvuong commented on docs/guides/unity-catalog-azure.md
> +    availability = "SPOT_AZURE"
```suggestion
    availability = "SPOT_WITH_FALLBACK_AZURE"
```

2022-09-22 14:28 UTC, MigQ2 commented
@nkvuong should we also change it in the [databricks_cluster docs example](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster#azure_attributes)? I will add it to this PR

2022-09-23 08:29 UTC, nkvuong approved these changes

2022-09-23 14:53 UTC, merged