Fixing condition on the s3 bucket
databricks/terraform-provider-databricks pull request #1694
Opened 2022-10-25 21:23 UTC by edmondo1984

2022-10-27 13:04 UTC, nfx requested changes

2022-10-27 13:04 UTC, nfx commented on aws/data_aws_bucket_policy.go
> +						Condition: map[string]map[string]string{
@edmondo1984 please make this field optional.

2022-10-27 13:04 UTC, nfx commented on aws/data_aws_bucket_policy.go
> +								"aws:PrincipalTag/DatabricksAccountId": d.Get("databricks_account_id").(string),
> Get your databricks-account-id. Go to the [account console](https://protect-us.mimecast.com/s/GK-NCOY0xwuNywrCER2IH?domain=docs.databricks.com) and click the in the bottom left corner. Under Account ID, select and copy the ID.

documentation meant the `E2 account id`, but in this data resource the `databricks_account_id` is AWS Account ID of Databricks

2022-10-31 16:39 UTC, edmondo1984 commented
> @edmondo1984 could you also add documentation? :)

Sure, is the only thing that's missing?

2022-10-31 17:02 UTC, nfx commented
@edmondo1984 yes, otherwise how users will discover this change? :)

2022-11-01 19:53 UTC, nfx approved these changes

2022-11-01 19:55 UTC, merged