add doc for `databricks_permission_assignment`
databricks/terraform-provider-databricks pull request #1880
Opened 2022-12-28 14:33 UTC by nkvuong

Closes #1823

2022-12-28 15:23 UTC, alexott requested changes

2022-12-28 15:23 UTC, alexott commented on docs/resources/mws_permission_assignment.md
> +  * `“USER”` - Can access the workspace with basic privileges.
these are unicode quotes that will generate a error if copied verbatim.

2022-12-28 15:23 UTC, alexott commented on docs/resources/mws_permission_assignment.md
> +* `principal_id` - Databricks ID of the user, service principal, or group. The principal ID can be retrieved using the SCIM API.
if data sources work with account SCIM api, we can mention them as well

2022-12-28 15:23 UTC, alexott commented on docs/resources/mws_permission_assignment.md
> +terraform import databricks_mws_permission_assignment.this workspace_id|principal_id
put quotes around `workspace_id|principal_id` - otherwise it will be treated as shell pipe

2022-12-28 15:23 UTC, alexott commented on docs/resources/permission_assignment.md
> +* `principal_id` - Databricks ID of the user, service principal, or group. The principal ID can be retrieved using the SCIM API.
same as above

2022-12-28 15:23 UTC, alexott commented on docs/resources/permission_assignment.md
> +  * `“USER”` - Can access the workspace with basic privileges.
same as above on unicode quotes

2022-12-29 15:46 UTC, alexott approved these changes
lgtm

2022-12-30 11:18 UTC, bricksterlad commented on docs/resources/permission_assignment.md
> +* `principal_id` - Databricks ID of the user, service principal, or group. The principal ID can be retrieved using the SCIM API, or using [databricks_user](../data-sources/user.md), [databricks_servi
If the principal is not yet assigned to the workspace, you can't use these data sources to retrieve the IDs using the workspace API, you will need to be an account admin to do that (using account API)

2023-01-09 18:33 UTC, merged