Fixed the issue of simple named objects not appearing in .tf output files
databricks/terraform-provider-databricks pull request #1889
Opened 2022-12-30 19:21 UTC by rohitkn

Changes were made to the `importables.go`, and `util.go` such that the `ResourceName(r)` function in context.go would return a normalized but **changed** name
Changes to the supplied names were very basic: 1) either changed an underscore `_` to a dash `-` or 2) `upper`cased the name.

2022-12-30 19:21 UTC, rohitkn commented
This is a fix for ISSUE number 1838

2023-01-02 07:09 UTC, alexott requested changes
it's not a real fix, but more a workaround. I was planning to fix this issue during this week as I'm back to office

2023-01-02 07:09 UTC, alexott commented on exporter/importables.go
> +					Name:     "inst-pool_" + ic.Importables["databricks_instance_pool"].Name(ic, r.Data),
although `-` is allowed in resources identifiers, they aren't considered idiomatic: https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md#identifiers

2023-01-02 07:09 UTC, alexott commented on exporter/importables.go
> +						Name:     strings.ToUpper(scope.Name), //strings.ToUpper fixes 1838
the lower-cased names are recommended.

2023-01-02 16:12 UTC, alexott commented
#1891 fixes it with smaller amount of changes

2023-01-09 18:51 UTC, closed without merging