Databricks on Azure with PrivateLink - Simplified deployment
databricks/terraform-provider-databricks pull request #1977
Opened 2023-02-03 11:12 UTC by yessawab

Adding a guide for a simplified deployment of Azure PL

2023-02-14 11:19 UTC, nkvuong requested changes
Some small comments, mostly around capitalization

2023-02-14 11:19 UTC, nkvuong commented on docs/guides/azure-private-link-workspace-simplified.md
> +      version = ">=2.83.0"
can we pin azurerm higher? it is currently at 3.x already

2023-02-14 11:19 UTC, nkvuong commented on docs/guides/azure-private-link-workspace-simplified.md
> +page_title: "Provisioning Databricks on Azure with PrivateLink - Simplified deployment"
if you run `make fmt-docs`, it will format all the Terraform snippets in the doc

2023-02-14 11:19 UTC, nkvuong commented on docs/guides/azure-private-link-workspace-simplified.md
> +Create a new Azure vnet and the different required subnets :
```suggestion
Create a new Azure VNet, the required subnets and associated security groups:
```

2023-02-14 11:19 UTC, nkvuong commented on docs/guides/azure-private-link-workspace-simplified.md
> +* A seperate private endpoint is used for web authentication
```suggestion
* A separate private endpoint is used for web authentication
```

2023-02-14 11:19 UTC, nkvuong commented on docs/guides/azure-private-link-workspace-simplified.md
> +  - Configure the private dns zone in order to add:
```suggestion
  - Configure the private DNS zone in order to add: 
```

2023-02-14 11:19 UTC, nkvuong commented on docs/guides/azure-private-link-workspace-simplified.md
> +-> **Note** This guide assumes that connectivity from the on-premises user environment is already configured using Expressroute or a VPN gateway connection.
```suggestion
-> **Note** This guide assumes that connectivity from the on-premises user environment is already configured using ExpressRoute or a VPN gateway connection.
```

2023-02-14 11:19 UTC, nkvuong commented on docs/guides/azure-private-link-workspace-simplified.md
> +This guide covers a [simplified deployment](https://learn.microsoft.com/en-us/azure/databricks/administration-guide/cloud-configurations/azure/private-link-simplified) to configure Azure Databricks w
```suggestion
This guide covers a [simplified deployment](https://learn.microsoft.com/en-us/azure/databricks/administration-guide/cloud-configurations/azure/private-link-simplified) to configure Azure Databricks with Private link:
```

2023-02-14 11:19 UTC, nkvuong commented on docs/guides/azure-private-link-workspace-simplified.md
> +page_title: "Provisioning Databricks on Azure with PrivateLink - Simplified deployment"
```suggestion
page_title: "Provisioning Databricks on Azure with Private Link - Simplified deployment"
```

It is Private Link (two words), let's just make sure it is consistent across this guide

2023-03-02 10:47 UTC, nkvuong approved these changes

2023-03-02 10:51 UTC, nfx commented on docs/guides/azure-private-link-workspace-simplified.md
> +![Private Link backend](../images/azure-private-link-simplified.png)
```suggestion
![Private Link backend](https://github.com/databricks/terraform-provider-databricks/raw/master/docs/images/azure-private-link-simplified.png)
```

2023-03-02 10:52 UTC, merged