Add acc tests for `databricks_schemas` data source
databricks/terraform-provider-databricks pull request #2074
Opened 2023-03-06 18:58 UTC by nkvuong

2023-03-06 19:11 UTC, nkvuong commented
acceptance test passed

2023-03-07 15:37 UTC, nfx requested changes

2023-03-07 15:37 UTC, nfx commented on catalog/data_schemas.go
> +			data.Ids = append(data.Ids, v.FullName)
don't change this

2023-03-07 15:58 UTC, nfx approved these changes

2023-03-07 15:58 UTC, merged