Add acc test for `databricks_tables` data source
databricks/terraform-provider-databricks pull request #2075
Opened 2023-03-06 20:09 UTC by nkvuong

2023-03-06 20:16 UTC, nkvuong commented
acc test passed

2023-03-07 15:30 UTC, nfx requested changes

2023-03-07 15:32 UTC, nkvuong commented on catalog/data_tables.go
> +				data.Ids = append(data.Ids, v.FullName)
because #2068 changed FullName -> Name, this fixes it by changing it back 😅

2023-03-07 15:48 UTC, nfx approved these changes

2023-03-07 15:48 UTC, merged