[PLAT-73750] Add TF for privateaccesssettings on GCP.
databricks/terraform-provider-databricks pull request #2088
Opened 2023-03-08 19:00 UTC by jessiedu-db

[PLAT-73750] Add TF for privateaccesssettings on GCP.

2023-03-08 19:05 UTC, nfx requested changes

2023-03-08 19:05 UTC, nfx commented on internal/acceptance/mws_private_access_settings_test.go
> +	t.SkipNow()
did you run this test?

2023-03-10 06:11 UTC, jessiedu-db commented on internal/acceptance/mws_private_access_settings_test.go
> +	t.SkipNow()
Thanks for reminding! I just ran it.

2023-03-10 06:11 UTC, jessiedu-db reviewed
Dummy.

2023-03-10 15:21 UTC, nfx approved these changes

2023-03-10 15:25 UTC, merged