fix edge cases for `databricks_permissions` resource
databricks/terraform-provider-databricks pull request #2158
Opened 2023-03-24 15:43 UTC by nkvuong

## Changes
Fix edge cases when setting permissions for root directory and password/token usage

Closes #2087, #2134

## Tests

- [ ] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

2023-03-24 17:31 UTC, nkvuong commented
acceptance tests passed on all 3 clouds

2023-03-28 08:12 UTC, nfx requested changes

2023-03-28 08:35 UTC, nkvuong commented on permissions/resource_permissions.go
> -								Summary:       "It is not possible to restrict any permissions from `admins`.",
I moved this logic down to Create (same place where we validate decreasing permission for current users), as it is possible to set permission on authorization/passwords for admins #2087

2023-03-31 10:40 UTC, nfx approved these changes

2023-03-31 10:57 UTC, merged