Add list functionality to mlflow models.
databricks/terraform-provider-databricks pull request #2174
Opened 2023-03-30 20:45 UTC by mberk06

## Changes

* Add `ModelListResponse` and `ModelListRequest` structs
* Add a List function to the model resource
* Add 3 tests

## Tests

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

2023-03-30 20:47 UTC, mberk06 commented
@alexott I'm starting with a list function for the mlflow exporter functionality - Rohit suggested this is a good first step. I've started working on other functionality as well. Thanks!

2023-03-31 10:59 UTC, nfx requested changes

2023-03-31 10:59 UTC, nfx commented on mlflow/resource_mlflow_model.go
> +func (a ModelsAPI) ListByFilter(filter string, order_by []string, page_token string) ([]Model, error) {
please use Go SDK, and not implement this manually.

probably a good idea to migrate those mlflow resources to SDK first.

2023-03-31 11:01 UTC, nfx commented on mlflow/resource_mlflow_model.go
> +func (a ModelsAPI) ListByFilter(filter string, order_by []string, page_token string) ([]Model, error) {
https://pkg.go.dev/github.com/databricks/databricks-sdk-go@v0.5.0/service/mlflow#RegisteredModelsAPI.ListAll

2023-03-31 20:05 UTC, mberk06 commented
Closing and moving to SDK functionality.

2023-03-31 20:05 UTC, closed without merging