Model migration to SDK with errors
databricks/terraform-provider-databricks pull request #2208
Opened 2023-04-10 15:55 UTC by mberk06

## Changes
Migrate the mlflow service to go SDK.

## Tests

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

2023-04-10 16:04 UTC, mberk06 commented
Hey @alexott. QQ about casting types. 

I'm getting the following error when running a [simple CREATE test](https://github.com/databricks/terraform-provider-databricks/blob/6468f91627aa007d6280da6d146aec5890e15d8b/mlflow/resource_mlflow_model_test.go#L21): `panic: interface conversion: interface {} is []interface {}, not []mlflow.RegisteredModelTag`, which can be found [here](https://github.com/databricks/terraform-provider-databricks/actions/runs/4658988394/jobs/8245322617?pr=2208#step:8:93). It seems like a simple type casting issue, so I can create a function that converts to `[]mlflow.RegisteredModelTag`, but that seems wrong. Any tips?

2023-04-17 09:27 UTC, nfx commented on mlflow/resource_mlflow_experiment_test.go
> +			name = "xyz"
why?

2023-04-17 14:59 UTC, nfx requested changes

2023-04-17 14:59 UTC, nfx commented on mlflow/resource_mlflow_experiment.go
> -	ArtifactLocation string `json:"artifact_location,omitempty" tf:"force_new,suppress_diff"`
1. re-implement suppress-diff by implementing `DiffSuppressFunc`
2. add `ForceNew` in the `StructToSchema` callback

2023-04-24 15:02 UTC, mberk06 commented on mlflow/resource_mlflow_model.go
> +			d.SetId(req.Name)                      // TODO: model is null - is it ok to set Id via request and not response?
@nfx I need to set the Id, however `w.RegisteredModels.Create(ctx, req)` returns a RegisteredModel of `nil`.  Is it ok to use the request params to get the model name?

2023-05-02 16:54 UTC, closed without merging