Added `force_destroy` to `databricks_external_location` resource
databricks/terraform-provider-databricks pull request #2353
Opened 2023-05-30 20:28 UTC by ehab-eb

## Changes
Fixes #2352 

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [x] covered with integration tests in `internal/acceptance`
- [x] relevant acceptance tests are passing
- [ ] ~~using Go SDK~~

2023-05-31 06:45 UTC, alexott requested changes
Please add acceptance test for this case.

2023-05-31 06:45 UTC, alexott commented on catalog/resource_external_location.go
> +				Default:  false,
this is not necessary, it's initialized to false anyway

2023-05-31 09:01 UTC, ehab-eb commented
@alexott I've added a test but tbh I'm a little lost when trying to understand the wrapper functions. Does the wrapper destroy by default when it's done or should I set the argument to `true`? I tried checking other deletion tests for reference but didn't find a consistent pattern to follow. 
It's my first time using Go so apologies if the questions are a little basic :)

2023-06-05 14:57 UTC, nkvuong commented on internal/acceptance/external_location_test.go
> +			name            = "external"
```suggestion
			name            = "external-{var.RANDOM}"
```

2023-06-05 18:52 UTC, nkvuong commented
acceptance tests passed

2023-06-05 18:53 UTC, nkvuong approved these changes
lgtm

2023-06-07 09:41 UTC, merged