Default run_if to ALL_SUCCESS
databricks/terraform-provider-databricks pull request #2435
Opened 2023-06-27 16:47 UTC by gaborratky-db

## Changes

Configure `ALL_SUCCESS` as the default for a task's `run_if` condition and add test coverage.

## Tests

- [ ] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

2023-06-27 17:21 UTC, alexott commented
@gaborratky-db you need to fix tests

2023-06-27 17:22 UTC, alexott requested changes
we need to fix tests

2023-06-27 18:38 UTC, alexott approved these changes
lgtm

2023-06-27 19:06 UTC, alexott commented on docs/resources/job.md
> +* `depends_on` - (Optional) A configuration block specifying another task this task depends on.
Should we say that could be 0 to N task dependencies?

2023-06-28 07:58 UTC, alexott approved these changes
lgtm

2023-07-17 08:23 UTC, gaborratky-db commented
@alexott fixed merge conflict, can it be merged?

2023-07-17 08:24 UTC, alexott commented
@nfx  fyi (as I don't have merge priveleges)

2023-07-17 08:25 UTC, alexott commented
@gaborratky-db code isn't compilable

2023-07-17 08:25 UTC, gaborratky-db commented
> @gaborratky-db code isn't compilable

oops, let me fix

2023-07-17 09:04 UTC, gaborratky-db commented
@nfx ready for you sir

2023-07-27 15:00 UTC, gaborratky-db commented on docs/resources/job.md
> +* `run_if` - (Optional) An optional value indicating the condition that determines whether the task should be run once its dependencies have been completed. When omitted, defaults to `ALL_SUCCESS`.
@mgyucht the docs are not live yet because the feature will only GA next week. Can we link to the `run_if` docs once the docs went live?

2023-08-01 23:21 UTC, gaborratky-db commented on docs/resources/job.md
> +* `run_if` - (Optional) An optional value indicating the condition that determines whether the task should be run once its dependencies have been completed. When omitted, defaults to `ALL_SUCCESS`.
REST API docs are going live once https://github.com/databricks/universe/pull/357228 is merged

2023-08-02 14:38 UTC, mgyucht commented on docs/resources/job.md
> +* `run_if` - (Optional) An optional value indicating the condition that determines whether the task should be run once its dependencies have been completed. When omitted, defaults to `ALL_SUCCESS`.
Yes, sounds good.

2023-08-02 14:46 UTC, merged