Add condition_task (private preview)
databricks/terraform-provider-databricks pull request #2459
Opened 2023-07-03 14:11 UTC by kanterov

## Changes
Add condition_task (private preview)

## Tests

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [x] using Go SDK

2023-07-03 14:56 UTC, alexott requested changes
overall looks good, just small change required

2023-07-03 14:56 UTC, alexott commented on jobs/resource_job.go
> -	DependsOn   []TaskDependency `json:"depends_on,omitempty"`
Let remove the original `TaskDependency` definition then

2023-07-03 14:59 UTC, alexott approved these changes

2023-07-04 08:05 UTC, lennartkats-db approved these changes

2023-07-06 07:43 UTC, merged