Added READ_VOLUME and WRITE_VOLUME to schema level grants
databricks/terraform-provider-databricks pull request #2529
Opened 2023-07-28 19:19 UTC by jl178

## Changes
According to the [Databricks documentation](https://docs.databricks.com/data-governance/unity-catalog/manage-privileges/privileges.html) & the [docs in this repo](https://github.com/databricks/terraform-provider-databricks/blob/6b7220ac4a5f8134fdaf4dc0ffdaf373bc370c00/docs/resources/grants.md?plain=1#L59), you should be able to have `READ_VOLUME` and `WRITE_VOLUME` at the schema level. However, this currently fails.

Example code:
```hcl
resource "databricks_grants" "volumes_grant" {
  schema = databricks_schema.volumes.id
  grant {
    principal  = databricks_group.group.display_name
    privileges = ["READ_VOLUME", "WRITE_VOLUME"]
  }
}
```

Error:

```
Error: READ_VOLUME is not allowed on schema
```

It seems like this was missed during [this PR](https://github.com/databricks/terraform-provider-databricks/pull/2399), even though the docs were updated correctly.

This is my first contribution, so please let me know if I am missing something! Thanks!

## Tests

- [x] `make test` run locally
- [ ] ~~relevant change in `docs/` folder~~
- [ ] ~~covered with integration tests in `internal/acceptance`~~
- [ ] ~~relevant acceptance tests are passing~~
- [ ] ~~using Go SDK~~

2023-07-28 19:26 UTC, nkvuong requested changes
Could you also add this to catalog level grants, as it is also supported via inheritance

2023-07-29 11:17 UTC, alexott approved these changes
lgtm

2023-07-31 12:44 UTC, nkvuong approved these changes

2023-08-01 17:59 UTC, mgyucht approved these changes

2023-08-01 18:11 UTC, merged