Documentation changes
databricks/terraform-provider-databricks pull request #2576
Opened 2023-08-10 11:54 UTC by nkvuong

## Changes
Some minor changes to our docs
- Add troubleshooting guide for grants/permissions config drifts
- Update authentication details in index.md

## Tests

- [ ] ~`make test` run locally~
- [x] relevant change in `docs/` folder
- [ ] ~covered with integration tests in `internal/acceptance`~
- [ ] ~relevant acceptance tests are passing~
- [ ] ~using Go SDK~

2023-08-10 12:01 UTC, alexott requested changes
small improvements would be nice to do

2023-08-10 12:01 UTC, alexott commented on docs/guides/troubleshooting.md
> +For both resources, each single instance should manages all the grants/permissions for a single object, etc. If there are multiple instances set up against an object, they will keep overwriting one a
Maybe change it to

```
For both resources, each single resource instance should manage all the grants/permissions for a given object, etc. If there are multiple resource instances set up against the same object, ... 
```

?

2023-08-10 12:01 UTC, alexott commented on docs/guides/troubleshooting.md
> +To prevent that, you need to have only one resource, and inside that resource, use [Dynamic Blocks](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks) to specify the varia
`one resource` -> `one resource instance` ?

2023-08-14 15:14 UTC, alexott approved these changes
lgtm

2023-08-22 14:24 UTC, mgyucht approved these changes

2023-08-22 14:34 UTC, merged