Use `terraform-field-dev` as code owner instead of `field-dev-ecosystem`
databricks/terraform-provider-databricks pull request #2718
Opened 2023-09-25 14:57 UTC by alexott

## Changes

The new team was created for work on Terraform code base

## Tests

- [ ] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

2023-09-25 15:33 UTC, nfx approved these changes

2023-09-25 15:41 UTC, nfx requested changes

2023-09-25 15:41 UTC, nfx commented on CODEOWNERS
> +*   @databricks/terraform-field-dev @databricks/eng-plat-auto-exp-reviewers
```suggestion
*   @databricks/field-dev-terraform @databricks/eng-plat-auto-exp-reviewers
```
to follow more standard group naming

2023-10-04 08:58 UTC, mgyucht approved these changes

2023-10-04 11:26 UTC, nfx approved these changes

2023-10-04 11:36 UTC, merged