Release v1.28.0
databricks/terraform-provider-databricks pull request #2793
Opened 2023-10-12 14:17 UTC by tanmay-db

## Changes

## Tests

- [ ] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

2023-10-12 14:19 UTC, tanmay-db commented on go.mod
> +	golang.org/x/exp v0.0.0-20231006140011-7918f672742d
I think we should also update the dependencies (`go get -u && go mod tidy`) on regular basis. Doing as part of release.

2023-10-12 14:32 UTC, alexott requested changes
#2765 is critical for one huge customer project

2023-10-12 14:33 UTC, alexott commented
#2744 is also asked by multiple customers

2023-10-16 09:56 UTC, alexott approved these changes

2023-10-16 10:05 UTC, mgyucht approved these changes

2023-10-16 10:18 UTC, merged