Added `databricks_automatic_cluster_update_workspace_setting` resource
databricks/terraform-provider-databricks pull request #3444
Opened 2024-04-09 09:46 UTC by nkvuong

## Changes
- Added `databricks_automatic_cluster_update_workspace_setting` resource
API does not seem to work at the moment

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [x] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [x] using Go SDK

2024-04-09 11:17 UTC, alexott approved these changes

2024-04-09 11:17 UTC, alexott commented on docs/resources/automatic_cluster_update_setting.md
> +  * A `window_start_time` block that defines the time of your maintenance window
Is it possible to specify a timezone? If no, what is the default timezone? API docs doesn't expose this information.

2024-05-10 14:10 UTC, harshshah-db approved these changes

2024-05-15 19:26 UTC, harshshah-db commented
@nkvuong can we merge this if all looks good? I want to enable the public api docs.

2024-05-16 06:32 UTC, alexott requested changes

2024-05-16 06:32 UTC, alexott commented on settings/all_settings.go
> +		"default_namespace":                  makeSettingResource[settings.DefaultNamespaceSetting, *databricks.WorkspaceClient](defaultNamespaceSetting),
There is a conflict here that we need to solve.

2024-05-16 06:32 UTC, alexott commented on settings/generic_setting.go
> +			}
We need to provide ability to customize schema as part of generic functions, not put specific customization into the generic settings definitions

2024-05-16 07:48 UTC, alexott commented on settings/generic_setting.go
> +}
Can we make it like this:

1. apply default schema customization by default
2. if custom function exist, apply it as well...

?

2024-05-16 09:29 UTC, alexott approved these changes

2024-05-16 09:33 UTC, merged