Rename lakehouse monitor to quality monitor
databricks/terraform-provider-databricks pull request #3584
Opened 2024-05-15 22:50 UTC by arpitjasa-db

## Changes

Update the `databricks_lakehouse_monitor` resource to `databricks_quality_monitor` to reflect naming changes in Go SDK.

## Tests

- [X] `make test` run locally
- [X] relevant change in `docs/` folder
- [X] covered with integration tests in `internal/acceptance`
- [X] relevant acceptance tests are passing
- [X] using Go SDK

2024-05-15 22:51 UTC, arpitjasa-db commented on catalog/resource_lakehouse_monitor.go
> +	return retry.RetryContext(ctx, qualityMonitorDefaultProvisionTimeout, func() *retry.RetryError {
NOTE: the Go SDK changes will go live with the next Go SDK release (currently scheduled for this Friday)

2024-05-15 23:27 UTC, xxxyyy3600 approved these changes
I am not very familiar with terraform code but renaming LGTM

2024-05-16 06:21 UTC, alexott requested changes
We have non-zero number of customer used this resource in the last 4 weeks.
We need to decide how to proceed with this change - introduce a new resource for example, or break after a communication.

2024-05-16 18:56 UTC, arpitjasa-db commented
> We have non-zero number of customer used this resource in the last 4 weeks. We need to decide how to proceed with this change - introduce a new resource for example, or break after a communication.

@alexott @xxxyyy3600 @mgyucht deprecated the old resource and created a new one instead. LMK if this works

2024-05-17 08:46 UTC, alexott commented
I converted to Draft until we get new SDK merged

2024-05-17 08:58 UTC, nkvuong commented on catalog/resource_online_table.go
> +	return retry.RetryContext(ctx, qualityMonitorDefaultProvisionTimeout, func() *retry.RetryError {
looks like a copy paste error

```suggestion
	return retry.RetryContext(ctx, onlineTableDefaultProvisionTimeout, func() *retry.RetryError {
```

2024-05-17 08:58 UTC, nkvuong commented on catalog/resource_online_table.go
> +	return retry.RetryContext(ctx, qualityMonitorDefaultProvisionTimeout, func() *retry.RetryError {
```suggestion
	return retry.RetryContext(ctx, onlineTableDefaultProvisionTimeout, func() *retry.RetryError {
```

2024-05-19 04:41 UTC, arpitjasa-db commented
> I converted to Draft until we get new SDK merged

Thanks @alexott, I saw the SDK hasn't been merged yet, what's the timeline on this? cc @mgyucht

2024-05-23 06:43 UTC, alexott approved these changes
code looks good, waiting for integration tests result

2024-05-23 07:09 UTC, alexott commented
Integration tests passed

2024-05-23 07:41 UTC, hectorcast-db approved these changes

2024-05-23 08:01 UTC, merged