Release v1.48.3
databricks/terraform-provider-databricks pull request #3752
Opened 2024-07-09 16:16 UTC by tanmay-db

### Internal Changes

 * Add Release tag ([#3748](https://github.com/databricks/terraform-provider-databricks/pull/3748)).
 * Improve Changelog by grouping changes ([#3747](https://github.com/databricks/terraform-provider-databricks/pull/3747)).
 * Upgrade Go SDK to v0.43.2 ([#3750](https://github.com/databricks/terraform-provider-databricks/pull/3750)).

### Other Changes

 * Add `databricks_schema` data source ([#3732](https://github.com/databricks/terraform-provider-databricks/pull/3732)).
 * Add new APIErrorBody struct and update deps ([#3745](https://github.com/databricks/terraform-provider-databricks/pull/3745)).
 * Added support for binding storage credentials and external locations to specific workspaces ([#3678](https://github.com/databricks/terraform-provider-databricks/pull/3678)).
 * Adds `databricks_volume` as data source  ([#3211](https://github.com/databricks/terraform-provider-databricks/pull/3211)).
 * Change TF registry ownership ([#3736](https://github.com/databricks/terraform-provider-databricks/pull/3736)).
 * Exporter: Emit directories during the listing only if they are explicitly configured in `-listing` ([#3673](https://github.com/databricks/terraform-provider-databricks/pull/3673)).
 * Exporter: export libraries specified as `requirements.txt` ([#3649](https://github.com/databricks/terraform-provider-databricks/pull/3649)).
 * Exporter: fix generation of `run_as` blocks in `databricks_job` ([#3724](https://github.com/databricks/terraform-provider-databricks/pull/3724)).
 * Exporter: use Go SDK structs for `databricks_job` resource ([#3727](https://github.com/databricks/terraform-provider-databricks/pull/3727)).
 * Fix invalid priviledges in grants.md ([#3716](https://github.com/databricks/terraform-provider-databricks/pull/3716)).
 * Make the schedule.pause_status field read-only ([#3692](https://github.com/databricks/terraform-provider-databricks/pull/3692)).
 * Refactored `databricks_cluster(s)` data sources to Go SDK ([#3685](https://github.com/databricks/terraform-provider-databricks/pull/3685)).
 * Renamed `databricks_catalog_workspace_binding` to `databricks_workspace_binding` ([#3703](https://github.com/databricks/terraform-provider-databricks/pull/3703)).
 * Run goreleaser action in snapshot mode from merge queue ([#3646](https://github.com/databricks/terraform-provider-databricks/pull/3646)).
 * Update cluster.md: add data_security_mode parameters `NONE` and `NO_ISOLATION` ([#3740](https://github.com/databricks/terraform-provider-databricks/pull/3740)).
 * Upgrade databricks-sdk-go ([#3743](https://github.com/databricks/terraform-provider-databricks/pull/3743)).
 * remove references to basic auth ([#3720](https://github.com/databricks/terraform-provider-databricks/pull/3720)).

2024-07-10 07:41 UTC, alexott requested changes
We need to split changelog further

2024-07-10 07:41 UTC, alexott commented on CHANGELOG.md
> + * Add `databricks_schema` data source ([#3732](https://github.com/databricks/terraform-provider-databricks/pull/3732)).
This is "New and improvements"

2024-07-10 07:41 UTC, alexott commented on CHANGELOG.md
> + * Exporter: use Go SDK structs for `databricks_job` resource ([#3727](https://github.com/databricks/terraform-provider-databricks/pull/3727)).
This is Exporter

2024-07-10 07:41 UTC, alexott commented on CHANGELOG.md
> + * Adds `databricks_volume` as data source  ([#3211](https://github.com/databricks/terraform-provider-databricks/pull/3211)).
This is "New and improvements"

2024-07-10 07:41 UTC, alexott commented on CHANGELOG.md
> + * Renamed `databricks_catalog_workspace_binding` to `databricks_workspace_binding` ([#3703](https://github.com/databricks/terraform-provider-databricks/pull/3703)).
This is "New and improvements"

2024-07-10 07:41 UTC, alexott commented on CHANGELOG.md
> + * Update cluster.md: add data_security_mode parameters `NONE` and `NO_ISOLATION` ([#3740](https://github.com/databricks/terraform-provider-databricks/pull/3740)).
Docs

2024-07-10 07:41 UTC, alexott commented on CHANGELOG.md
> + * remove references to basic auth ([#3720](https://github.com/databricks/terraform-provider-databricks/pull/3720)).
Docs

2024-07-10 13:55 UTC, tanmay-db commented
Hi @alexott, yeah, I was looking into test infra issues, just updated the changelog.

2024-07-10 14:01 UTC, hectorcast-db approved these changes

2024-07-10 14:08 UTC, alexott approved these changes

2024-07-17 13:16 UTC, alexott commented
We need to update this changelog as we merged a number of changes:

* Exporter: https://github.com/databricks/terraform-provider-databricks/pull/3764, 
* Features: https://github.com/databricks/terraform-provider-databricks/pull/3762

2024-07-17 13:28 UTC, tanmay-db commented
@alexott yes, one more fix got merged recently: https://github.com/databricks/terraform-provider-databricks/pull/3784 for nightly tests. I will update it.

2024-07-18 11:27 UTC, tanmay-db commented
update: Waiting for https://github.com/databricks/terraform-provider-databricks/pull/3690 to be merged before doing the release.

2024-07-19 15:18 UTC, tanmay-db commented
The release has been rebased + updated changelog for recently merged commits. There are few test failures that are known issues. Also some more failures in gcp-prod but they doesn't seem related to recent changes (they passed yesterday). Going ahead with release since these are mostly test infra issues.

2024-07-19 15:22 UTC, merged